#ifndef XPU_DEFINES_H
#define XPU_DEFINES_H

#define XPU_IS_CPU XPU_DETAIL_IS_CPU
#define XPU_IS_CUDA XPU_DETAIL_IS_CUDA
#define XPU_IS_HIP XPU_DETAIL_IS_HIP
#define XPU_IS_SYCL XPU_DETAIL_IS_SYCL

#define XPU_IS_HIP_CUDA (XPU_IS_CUDA || XPU_IS_HIP)

#define XPU_D XPU_DETAIL_DEVICE_SPEC

#define XPU_FORCE_INLINE XPU_DETAIL_FORCE_INLINE

#define XPU_COMPILATION_TARGET XPU_DETAIL_COMPILATION_TARGET

#define XPU_CUDA_HAS_BLOCK_ATOMICS XPU_DETAIL_HAS_BLOCK_ATOMICS

#include "detail/defines.h"

#endif
